In [2]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=[1,2,3,4,5] , y=[3,4,5,6,7] , mode='markers' ))
fig.show()

In [3]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=[1,2,3,4,5] , y=[3,4,5,6,7] , mode='lines' ))
fig.show()

In [4]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Bar(x=[1,2,3,4,5] , y=[3,4,5,6,7]  ))
fig.show()

In [5]:
x = [1,2,3,3,4,4,5,5,6,6,7,78,9,9,0,8,9,8,7,6,5,1,2,2,23,34,45,5]

In [6]:
fig = go.Figure(data = [go.Histogram(x = x)])
fig.show()

In [7]:
import seaborn as sns

In [8]:
tips = sns.load_dataset('tips')

In [9]:
fig = go.Figure(data = [go.Histogram(x = tips.total_bill)])
fig.show()

In [10]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill, y=tips.tip , mode='markers' ))
fig.show()

In [12]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill, y=tips.tip , mode='markers' ,marker_size =10*tips['size'] ))
fig.show()

In [13]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [14]:
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [15]:
tips['size']

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [16]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=tips.total_bill, y=tips.tip , mode='markers' ,z =tips['size'] ))
fig.show()

In [17]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[1,2,3,4], y=[5,6,5,7], mode='lines' ,z =[2,3,4,2] ))
fig.show()

In [18]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[1,2,3,4], y=[5,6,5,7], mode='markers' ,z =[2,3,4,2] ))
fig.show()

In [19]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=tips.total_bill, y=tips.tip , mode='lines' ,z =tips['size'] ))
fig.show()